agonyforge/arbitrader

- src/main/java/com/r307/arbitrader/TradingService.java
Closes #27 
Replaces some code accidentally removed that is necessary for Quoine and Coinbase Pro to properly initialize.
> Long leverage

- src/main/java/com/r307/arbitrader/TradingService.java
* Improved handling of dynamic vs. configured trading fees.
* Shuffle the exchanges and pairs so no single combination is always first to be evaluated.
* Catch an `IOException` that was generating a decent amount of log spam from a particularly unreliable exchange.
* Display updated account balances when positions are closed.
* No longer hack `executeOrderPair()` by reversing the parameters. Added a boolean for opening vs. closing positions so it can have better logic.
* Add a flavor of `getAccountBalance()` that can get it for any currency, rather than only the "home" currency.
> Some combined branches

- src/main/java/com/r307/arbitrader/TradingService.java
- src/test/java/com/r307/arbitrader/TradingServiceTest.java
XChange is a great library but it's very complex and has a lot of final classes that can't be mocked. Exchanges are huge object graphs with an enormous number of permutations, and to test this beast we're going to need to generate a lot of different Exchanges in different configurations. A Builder is going to go a long way toward making that a little more pleasant.
> Corralling complexity, one iteration at a time

- src/main/java/com/r307/arbitrader/exception/OrderNotFoundException.java
- src/main/java/com/r307/arbitrader/logging/SlackAppender.java
- src/main/java/com/r307/arbitrader/logging/SpringContextSingleton.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/resources/slack-appender.xml
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
* Summary shows spreads above 0 when not in market
* Summary shows the active trade and exit target when in market
* Moved some classes into packages
> Log a summary every 6 hours

- src/main/java/com/r307/arbitrader/service/TradingService.java
Volume computation wasn't working for some exchanges, and would come out to zero.
> Exit trade volume

- application.example.yaml
- src/main/java/com/r307/arbitrader/config/NotificationConfiguration.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Configurable threshold for when the bot will display slow ticker warnings.
> Configurable ticker warning

- build.gradle
- src/main/java/com/r307/arbitrader/service/ActivePosition.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
Persist the state of the bot in a file that can be reloaded if the bot needs to be restarted.
> Persist state

- src/main/java/com/r307/arbitrader/service/TradingService.java
> Catch ExchangeExceptions and print less frightening warnings

- src/main/java/com/r307/arbitrader/DecimalConstants.java
- src/main/java/com/r307/arbitrader/service/ExchangeFeeCache.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/ExchangeBuilder.java
- src/test/java/com/r307/arbitrader/service/ExchangeFeeCacheTest.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Fixes #74 
Also caches the result of dynamic fee lookups to reduce the number of API calls.
> Respect trade minimum

- CONTRIBUTING.md
- README.md
* Trim down the README and move the bulk of it into the Wiki, where we can make use of having multiple pages.
* Add a CONTRIBUTING.md document.
> Documentation Updates

- buildspec.yml
* Specific conditions for CodeBuild and GitHub
* Treat anything else as a "snapshot"
* Move all tagging and pushing into post_build
> Build adjustments

- src/main/java/com/r307/arbitrader/service/TradingService.java
Fixes #84 
The loop used an and instead of an or, so it only waited for the first of the two orders to fill.
Added a notification every 30 seconds if the wait starts to take a long time.
> Wait for both orders to fill

- CONTRIBUTING.md
* Fixed a problem with the list at the end of the doc
* More detail about how to select something to work on
* More detail about how to begin work on a new feature
> Small update

- build.gradle
May version bump for XChange. This version of XChange includes a fix I contributed for Gemini that will remove a warning during startup.
> Update to the latest XChange version

- application.example.yaml
- src/main/java/com/r307/arbitrader/DecimalConstants.java
- src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
- src/main/java/com/r307/arbitrader/service/ErrorCollectorService.java
- src/main/java/com/r307/arbitrader/service/ExchangeService.java
- src/main/java/com/r307/arbitrader/service/TickerService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/TickerStrategy.java
- src/test/java/com/r307/arbitrader/ExchangeBuilder.java
- src/test/java/com/r307/arbitrader/service/ErrorCollectorServiceTest.java
- src/test/java/com/r307/arbitrader/service/ExchangeFeeCacheTest.java
- src/test/java/com/r307/arbitrader/service/ExchangeServiceTest.java
- src/test/java/com/r307/arbitrader/service/TickerServiceTest.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
- src/test/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategyTest.java
- src/test/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategyTest.java
* Extract some functionality into smaller, more testable classes.
* Add an error reporter to summarize non-critical error messages.
> Service refactor

- application.example.yaml
> Example configs for remaining supported exchanges

- src/main/java/com/r307/arbitrader/service/TradingService.java
* Remove profit estimation and just subtract starting balance from current balance - closes #64
* Fix notification when limit orders don't close so that you get a message every 5 minutes
> Fix profit estimation

- build.gradle
- src/main/java/com/r307/arbitrader/service/ErrorCollectorService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/resources/application.yaml
* Support for Cobinhood exchange
* Set order volume based on exchange metadata, when available
* Quiet noncritical stack traces from rescu
> A few new features

- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Accidentally used `Optional.of()` instead of `Optional.ofNullable()` so my fix broke. This time I included a test!
> Fix new NPE from getVolumeForOrder()

- build.gradle
- src/main/java/com/r307/arbitrader/logging/SpringContextSingleton.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
https://stackoverflow.com/questions/12218515/unpredictability-of-the-bigdecimaldouble-constructor
> stop using "unpredictable" BigDecimal constructor

- build.gradle
- src/main/java/com/r307/arbitrader/service/SpreadService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/model/ActivePosition.java
- src/main/java/com/r307/arbitrader/service/model/Spread.java
- src/main/java/com/r307/arbitrader/service/model/TradeCombination.java
- src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
* Created a daily summary of min/max spreadIns and spreadOuts which may be useful for adjusting your configuration of entry/exit spread thresholds over time.
* Slowly pulling apart the TradingService into a bunch of smaller, simpler, more testable services.
> extract the SpreadService out

- application.example.yaml
- build.gradle
- src/main/docker/codebuild/Dockerfile
- src/main/docker/local/Dockerfile
- src/main/java/com/r307/arbitrader/service/TickerService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
- src/test/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategyTest.java
> Kraken stream

- src/main/java/com/r307/arbitrader/service/TradingService.java
Removed Map<TradeCombination, BigDecimal> missedTrades
This is WIP - looking forward for your feedback :)
> Extracted some methods out of TradingService#tick and simplified a bit the flow

- src/main/java/com/r307/arbitrader/service/TradingService.java
Refactor accidentally broke computation of the volume on the short exchange.
> fix entry volume computation

- buildspec.yml
Forgot to push `latest` to GitHub.
> push a latest tag to GHCR on PR merges

- buildspec.yml
One more change:
* The GHCR version of the `latest` tag needs to be tagged separately.
* Make sure to push `latest` tags last, so they are in fact the latest.
> GitHub packages

- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
This pull request is built on top of https://github.com/scionaltera/arbitrader/pull/264
> Remove temp fix for gemini exchange

- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
This fix an issue where when calling subscribeAll the map of the observable would return a null value causing a NPE which would cause the streaming exchange to unsubscribe the ticker on (at least) some exchanges
> Fix subscribeAll throw NPE

- src/main/java/com/r307/arbitrader/service/TickerService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
Currency pairs were no longer being added to trade combinations, so while we were collecting tickers we would never act on them. Also the 6 hour summary was not displaying any entries.
> correctly setup trade combinations

- src/main/java/com/r307/arbitrader/Utils.java
- src/main/java/com/r307/arbitrader/service/ConditionService.java
- src/main/java/com/r307/arbitrader/service/ErrorCollectorService.java
- src/main/java/com/r307/arbitrader/service/ExchangeFeeCache.java
- src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
- src/main/java/com/r307/arbitrader/service/TickerService.java
- src/main/java/com/r307/arbitrader/service/TradingScheduler.java
- src/main/java/com/r307/arbitrader/service/model/ArbitrageLog.java
- src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
* the Exchange constructor we were using has become deprecated in XChange
* getCurrencyPair() has become deprecated in XChange
* unnecessary StringBuilders converted into String addition
* some unnecessary imports removed
* a comment or two edited
> some general cleanup

- build.gradle
* bump spring version
* remove tyrus client dependency
> resolve dependency PRs

- src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
> clean up unwanted artifacts after test class runs

- .gitignore
- src/main/java/com/r307/arbitrader/service/TradingService.java
* gitignore .arbitrader folder
* reduce log messages to DEBUG
* adjust a comment
> misc changes

- src/main/java/com/r307/arbitrader/service/ExchangeService.java
> Cache Exchange's fee on the last fall back return - when calling ExchangeService#getExchangeFee

- application.example.yaml
- src/main/java/com/r307/arbitrader/config/PaperConfiguration.java
- src/main/java/com/r307/arbitrader/config/TradingConfiguration.java
- src/main/java/com/r307/arbitrader/service/SpreadService.java
- src/main/java/com/r307/arbitrader/service/TradingScheduler.java
- src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
* active flag for paper trading
* a log message when paper trading is enabled
* a new option to enable notifications when spreadIns and spreadOuts hit high/low water marks
> some new configuration options

- src/main/java/com/r307/arbitrader/service/SpreadService.java
Adds a visual indicator to the record high and record low messages to show whether for that pair the maximum spreadIn and minimum spreadOut have crossed yet. When they cross, that means that _in the spreads we have observed so far_ we have seen a profitable range. If you had managed to enter the market at the maximum spreadIn and exit at the minimum spreadOut you would have made money. Of course past performance is not an indicator of future performance, but it's a good indication of whether opportunities could possibly exist for a pair in the data we've seen so far.
In the future this check could be used as a very quick way to avoid spending time on processing pairs that haven't ever had the potential to generate a profit. It also ties back to the work I was doing to automatically select …
> add emojis to record breaker log messages

- src/main/java/com/r307/arbitrader/Utils.java
- src/main/java/com/r307/arbitrader/service/ExchangeService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
This PR solves issue https://github.com/agonyforge/arbitrader/issues/364
> Prevent the bot from starting up if the account wallet is not empty for any coin in the trading pair list

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/docker/codebuild/Dockerfile
- src/main/docker/local/Dockerfile
The build was failing when compiled with Java 16. Reported by Blacko on Discord.
* Updated Gradle to 7.0.2
* Updated Pitest to 1.6.6
* Removed stats plugin because latest version doesn't work in Windows
* Switched to Palantir's Docker plugin because the old one is no longer maintained
* Tested using Amazon Corretto 16 but reverted to 8 after confirming it can work
I'm not ready to increase the required Java version yet, but I'm glad to know that it works in the latest version.
> Compatibility with JDK 16
