agonyforge/arbitrader

- src/main/java/com/r307/arbitrader/TradingService.java
I consider this change the first step toward more rigorous verification that the bot is reporting reliable numbers. It'll print out the account balances and their sum before entering the two positions, and again after exiting the two positions. Assuming the trades all opened and closed successfully the sums of the account balances will show for sure whether you gained or lost money overall. Once I have this kind of reporting I can start tracking back through the earlier estimates to make sure the math all adds up like it ought to.
> Log exchange balances on opening and closing trades

- docker-compose.yaml
- src/main/java/com/r307/arbitrader/service/TradingService.java
Fixes #61 
If the state file doesn't exist (e.g. on the first run) docker-compose will create a directory with the same name and mount that into the container. The bot will then be unable to write the file when it needs to. This makes a change to `docker-compose.yaml` and the path for the state file so that we now have a dot directory for Arbitrader which may be empty but can be mounted into the container and the bot will be able to write into it.
> Mount a dot folder instead of a file for metadata.

- src/main/java/com/r307/arbitrader/service/TradingService.java
Ran into this for the first time last night. This change protects against NPEs and refactors a little duplicate code into a method.
> Reject tickers with missing bid/ask values

- build.gradle
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/model/ActivePosition.java
- src/main/java/com/r307/arbitrader/service/model/TradeCombination.java
- src/test/java/com/r307/arbitrader/service/model/ActivePositionTest.java
- src/test/java/com/r307/arbitrader/service/model/TradeCombinationTest.java
* Pre-compute the active trade combinations on startup instead of doing it every tick
* Only fetch tickers that are actually being used for trading
> Optimize to reduce API calls

- src/main/java/com/r307/arbitrader/service/ConditionService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/model/ActivePosition.java
- src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Force the bot to close current positions immediately by creating an empty file named `force-close` in the directory where the bot is running. This can be useful if you are tired of waiting for a trade to close. 
It is also going to be very useful for me to test the logic around closing trades much more quickly than I have been able to in the past.
Fixes #35
> Force close position

- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Exiting positions on some exchanges wasn't working reliably because the trade volume was being computed as greater than the available currency. The old algorithm was:
* Check the open order on the exchange and use its volume
* Failing that, use the volume we remembered from when we entered the position
Unfortunately for Poloniex (possibly others) we couldn't look up the order and the available balance was less than the entry volume due to fees. This PR adds a middle step to check the account balance in the base cryptocurrency to see if we can get the total available amount. If it comes out to zero or throws an exception, only then do we fall back to the remembered volume.
> Accurate exit volumes

- buildspec.yml
It's trying to set a bad tag on the Docker image when it doesn't need to. This looks like something that used to work (it failed to set the tag but the build still completed successfully) but has changed so it now fails the entire build.
Unfortunately the only way to test this is to merge PRs into master, so this could end up taking a few tries...
> PR merge builds appear to be failing

- src/main/java/com/r307/arbitrader/service/ConditionService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
* Fixes #68
* Placing an empty file called "exit-when-idle" in Arbitrader's working directory will make it exit the next time there is no active trade
> Exit when idle

- buildspec.yml
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
Some exchanges require trade sizes to be specific volumes (e.g. multiples of 0.01).
Fortunately XChange has a setting in the exchange metadata that indicates the lot size. This new feature will use that metadata, if it is present, to round off trades for that exchange to meet the required lot size.
Unfortunately none of the exchanges I use have this requirement so I can't test any live trades. This PR is blocked until @sanitariu or somebody else from the community has an opportunity to test it using an exchange that requires it, such as Binance.
To test, you may build from the `stepped-lot-size` branch or you can use the `scionaltera/arbitrader:stepped-lot-size` Docker tag. Post your log here to show that it used the correct lot sizes for a trade. Feel free to scrub other information like …
> Stepped lot size

- src/main/java/com/r307/arbitrader/service/TradingService.java
Avoid several places where we could throw a `NullPointerException` if an exchange does not have a `CurrencyMetaData` for the trade we're trying to make.
> Step size npe

- build.gradle
XChange 4.3.19 includes my fix for warnings from Bitflyer about badly formatted date strings.
> Bump to XChange 4.3.19

- .gitignore
- build.gradle
- src/main/java/com/r307/arbitrader/service/ConditionService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
Allows a user to create a file named 'blackout' in the current working directory with "extended" ISO-8601 dates indicating that the bot should not trade during the specified times. Each line of the file should look like this:
```
Cool Coins,2011-12-03T10:15:30+01:00,2011-12-03T12:15:30+01:00
```
The above indicates that for the exchange "Cool Coins" from 10:15 to 12:15 on Dec 3, 2011 we should not trade. The file can have as many lines as you wish and may safely be changed or deleted while the bot is running. Each time the bot wants to trade, it will attempt to read the file and check whether the current time is within any of the specified blackout windows.
> Trading Blackout Windows

- application.example.yaml
- build.gradle
- src/main/java/com/r307/arbitrader/config/JsonConfiguration.java
- src/main/java/com/r307/arbitrader/config/TradingConfiguration.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/model/ActivePosition.java
- src/main/resources/application.yaml
- src/test/java/com/r307/arbitrader/ExchangeBuilder.java
- src/test/java/com/r307/arbitrader/service/ExchangeFeeCacheTest.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
- src/test/java/com/r307/arbitrader/service/model/ActivePositionTest.java
This is a good option to limit the effect of ongoing fees from the exchange where you have your short position. If you leave that position open long enough it can easily eat up all the profit from your trades, and currently Arbitrader is not capable of tracking those costs.
Closes #30
> optional timeout for how long an open position may remain open

- .gitignore
- build.gradle
- src/main/java/com/r307/arbitrader/service/TradingService.java
I got `SocketTimeoutException`s fetching the `OpenOrders` while waiting for an order to fill and it jumped me out of the loop, tried to enter another trade and died because there wasn't enough available balance (one of the trades hadn't been closed). This solution is verbose but won't allow a broken connection from the long exchange to exit the loop or skip checking the short exchange.
> isolate stray IOEs to avoid jumping out of the loop

- build.gradle
Spring Boot to 2.3.4.RELEASE
XChange to 5.0.3
Also fixed a warning in build.gradle for a deprecated method.
> catch up on Spring and XChange versions

- build.gradle
- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
- src/test/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategyTest.java
Respect the homeCurrency configuration field when using a StreamingExchange class
On the streaming class, if an exchange has the homeCurrency set in the configuration yaml file this was not taking in consideration (missing a call `to exchangeService.convertExchangePair(exchange, pair)`)
For `GeminiStreamingMarketDataService` on v5.0.2 we must pass on a value to the args parameter or it will throw a null pointer exception (I fixed it on the XChange side, please see: https://github.com/knowm/XChange/pull/3761). So as soon as the new version is released we can clean up this if else code.
On line 74 (`exchange.getStreamingMarketDataService().getTicker(exchangeService.convertExchangePair(exchange, pair), 10);`) I choose the number 10 for no special reason. Please let me know if it should be a …
> Fix NPE on XData (v5.0.2) for Gemini Streaming Exchange when args is empy

- buildspec.yml
- src/main/docker/codebuild/Dockerfile
- src/main/docker/local/Dockerfile
Publish Docker images to the new [GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/) in addition to Docker Hub.
With Docker Hub's new [rate limits](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) on pulls going into effect it may be that some users will need or want an alternative way to get containers. I wanted to try this feature out anyway, and it's cool that it's part of GitHub. It kind of brings everything back to one place.
For the time being we'll just publish the images to both places and the default Docker Compose configuration will still pull from Docker Hub. If you exhaust your pulls there you would be able to switch. At some point down the line we may choose one or the other.
> GitHub packages

- build.gradle
- src/main/java/com/r307/arbitrader/Utils.java
- src/main/java/com/r307/arbitrader/config/AppConfig.java
- src/main/java/com/r307/arbitrader/service/ExchangeService.java
- src/main/java/com/r307/arbitrader/service/SpreadService.java
- src/main/java/com/r307/arbitrader/service/TickerService.java
- src/main/java/com/r307/arbitrader/service/TradingScheduler.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/main/java/com/r307/arbitrader/service/event/StreamingTickerEventListener.java
- src/main/java/com/r307/arbitrader/service/event/StreamingTickerEventPublisher.java
- src/main/java/com/r307/arbitrader/service/model/TickerEvent.java
- src/main/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
- src/main/java/com/r307/arbitrader/service/ticker/TickerStrategyProvider.java
- src/test/java/com/r307/arbitrader/ExchangeBuilder.java
- src/test/java/com/r307/arbitrader/service/ExchangeServiceTest.java
- src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
- src/test/java/com/r307/arbitrader/service/TickerServiceTest.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
- src/test/java/com/r307/arbitrader/service/ticker/ParallelTickerStrategyTest.java
- src/test/java/com/r307/arbitrader/service/ticker/SingleCallTickerStrategyTest.java
- src/test/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategyTest.java
Refactored SpreadService, TradingService, ExchangeService, ExchangeService.
Added class TradingScheduler
Currently, the app does not start due to a cyclic dependency:
```
┌─────┐
|  exchangeService defined in file [/(...)/arbitrader/build/classes/java/main/com/r307/arbitrader/service/ExchangeService.class]
↑     ↓
|  parallelTickerStrategy defined in file [/(...)/arbitrader/build/classes/java/main/com/r307/arbitrader/service/ticker/ParallelTickerStrategy.class]
└─────┘
```
This is due to the fact `TickerStrategy#getTickers` implemtations requiring a call to `ExchangeService#convertExchangePair`. Ideally we should remove the need to call `ExchangeService#convertExchangePair` from within `TickerStrategy` implementations. This way we remove the cyclic dependency.
Do you have suggestions?
> Reactive way to calculate trades for tickers received via websockets

- src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
The MarketDataService#getTicker() method has a vararg parameter that is mostly unused, and Arbitrader has simply omitted it up to this point for all exchanges. Unfortunately the streaming MarketDataService for Gemini has a bug where a default value is zero and literally any value greater than zero would solve our problem. If we could just pass a "1" to its `getTicker()` method...
This feature allows a YAML list in your configuration file of constant values to be passed into this `getTicker()` method for a given exchange. It allows a clean workaround of this Gemini bug and I think it may be useful for working around other similar bugs in the future. While the "correct" solution is probably to change the default value in XChange (and I plan to submit a PR for that too) this feature will …
> pass custom arguments to `getTicker()`

- src/main/java/com/r307/arbitrader/service/TradingScheduler.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
Looks like the ActivePosition got split across TradingService and TradingScheduler which is making the behavior of tracking active positions act strangely, especially if you have quit and restarted the program, because it is being tracked independently in two places. This PR moves ownership of the ActivePosition over to TradingService and makes TradingScheduler access it via getter and setter.
> unify active position

- src/main/java/com/r307/arbitrader/service/ConditionService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/ConditionServiceTest.java
You can now create a file while the bot is running and tell it to open a trade on a specific currency, between two specific exchanges, even if the spread isn't good enough to trade automatically.
The intended use for this is to aid in testing when the market isn't cooperating. I've been trying to test trade exits on BitFlyer for weeks now but my bot hasn't wanted to trade. Now I can make it open the trade anyway and use `force-close` to make it exit, so I can test the trade volume logic regardless of market conditions.
> Force a trade to open

- src/main/java/com/r307/arbitrader/service/TradingService.java
This happened to me when the exchange returned 503 the bot kept running and but I wasn't sure if the bot was aware there were open orders. This will prevent it and force the bot to request again the open orders from the exchange
> Prevent the bot to enter an unknown state when receiving a 5XX response for a getOpenOrders request

- src/main/java/com/r307/arbitrader/service/TradingService.java
instead of assuming it's always 8
My bot tried to trade XRP/USD on CoinbasePro last night and it failed because Coinbase only allows a scale of 6.
> get currency scale from exchange metadata

- src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
The paper trading fee calculation was incorrect: the exchange fee is expressed in percentage, hence need to be divided by 100 before multiplying.
> Correct fee calculation

- application.example.yaml
- src/main/java/com/r307/arbitrader/config/PaperConfiguration.java
- src/main/java/com/r307/arbitrader/service/paper/PaperAccountService.java
- src/main/java/com/r307/arbitrader/service/paper/PaperExchange.java
- src/main/java/com/r307/arbitrader/service/paper/PaperStreamExchange.java
- src/main/java/com/r307/arbitrader/service/paper/PaperTradeService.java
- src/test/java/com/r307/arbitrader/service/paper/PaperTradeServiceTest.java
This commit:
- enables the FeeComputation.CLIENT exchanges to work with PaperTrading. The calculation is the opposite to the addFees/subtractfees method.
- unit tests the PaperTradeService.fillOrder method. The FeeComputation.CLIENT test need real data.
- keep track of all the balances of the PaperAccountService, not only the cash balance
> Enhance paper AccountInfo with balance info + paper trading FeeComputation.CLIENT

- src/main/java/com/r307/arbitrader/config/NotificationConfiguration.java
- src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
The '-' is already appended to the groupId on the `setGroupId`. I forgot to remove it from here
> Remove duplicated '-' on the groupId when sending a message via Telegram

- build.gradle
- src/main/java/com/r307/arbitrader/service/ticker/StreamingTickerStrategy.java
This fixes #357 .
Quote from @scionaltera, the cause is basically:
> Another possibility is that we're putting the wrong CurrencyPairs in the ProductSubscription in StreamingTickerStrategy#getTickers() due to the homeCurrency setting. The code in the BinanceStreamingMarketDataService checks to see if the ticker you're asking for is in the original list created when the connection was first connected. If, for example, we put "BTC/USD" in at that point and "BTC/USDT" in later, or the reverse, that could cause this problem too.
Also upgraded to 5.0.6 so might be better merged after #354 .
> fix stream binance bug due to homeCurrencies

- src/main/java/com/r307/arbitrader/service/ExchangeService.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
In some cases the `volume` may be null and a NPE is thrown. To avoid that we do a null check before comparing the value of `volume`.
If `volume` is null we fallback to getting the amount of currency base we have in our account. The issue is here, before this PR we would always use USD scale, even for crypto currencies.
> On TradingService#getVolumeForOrder null check volume and use currency.base scale instead of USD scale

- application.example.yaml
- src/main/java/com/r307/arbitrader/config/ExchangeConfiguration.java
- src/main/java/com/r307/arbitrader/service/ExchangeService.java
The feature to prevent Arbitrader from starting if an account has a non-zero crypto balance in it was a good idea but it led me into an impossible situation: my BitFlyer account has 0.00000001 BTC in it, and BitFlyer's minimum trade size is 0.001. I've tried buying crypto and selling all of it to get down to zero and no matter what I do that one last little satoshi remains.
So... I tried making it look at the exchange metadata to figure out the minimum trade size and compare against that instead of zero. Of course the metadata for BitFlyer is missing, so it defaults to zero.
So here we are. I have added a new configuration option that lets you set the minimum allowed balance for a currency on an exchange to whatever you want if the bot won't start because of a tiny bit of crypto you can't …
> configurable minimum balances

- application.example.yaml
- build.gradle
- src/main/java/com/r307/arbitrader/config/TradingConfiguration.java
- src/main/java/com/r307/arbitrader/service/SpreadService.java
- src/main/java/com/r307/arbitrader/service/TradingScheduler.java
- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/service/SpreadServiceTest.java
This changes the configuration from entrySpread / exitTarget to:
- entrySpreadTarget: the effective spread to meet before entering a trade
- exitSpreadTarget: the effective spread to meet before closing a trade
- minimumProfit: the profit in percentage to get before closing a trade. Default to 0.
If exitSpreadTarget is set, the minimumProfit property is ignored. 
We calculate the real entry and exit spread targets from those configurations.
> Effective spreads

- src/main/java/com/r307/arbitrader/service/TradingService.java
- src/test/java/com/r307/arbitrader/ExchangeBuilder.java
- src/test/java/com/r307/arbitrader/service/TradingServiceTest.java
...instead of the CurrencyMetaData which seems to have the wrong values for what we're doing.
This is intended to fix errors that have started to pop up with Kraken saying that we're using the wrong number of decimal places for several currency pairs.
> Use the CurrencyPairMetaData to find the price scale

- src/main/java/com/r307/arbitrader/service/ExchangeService.java
- src/main/java/com/r307/arbitrader/service/TradingScheduler.java
Prevent the bot from starting if the user set a fixed exposure and the account balance is lower than the defined fixed exposure.
Otherwise the bot will start and then get a `Not Enough Balance` exception on the first trade it tries to execute on that exchange.
> Prevent the bot from starting if an exchange account balance is lower than the defined fixed exposure

- src/main/java/com/r307/arbitrader/service/ExchangeService.java
For some reason I started to get a NPE on start up for some coins on Bitstamp exchange. This should fix it
> Null check CurrencyPairMetaData.getMinimumAmount() - for some currency pairs it may be null

- src/main/java/com/r307/arbitrader/service/NotificationServiceImpl.java
Due to a bug in the `NotificationServiceImpl` class, if there is a forced exit or a timeout exit the notification message is missing the trade details.
Example of a message sent via telegram: [https://i.imgur.com/GUB5kRs.png](url)
As you can see, it is missing the:
Entry spread,  Exit spread target, Market neutrality rating and so on...
> Bugfix: Send the whole message text when exiting a position due to timeout or forced exit command

- src/main/java/com/r307/arbitrader/service/TradingService.java
Instead of (always) fetching open orders for both exchanges we now only fetch for open orders for the exchange(s) that actually has an open order
> Only fetch open orders for the exchange that actually has an open order

- README.md
See https://github.com/dependabot/dependabot-core/issues/1912
Will add it back in when the new Dependabot supports a badge.
> temporarily remove dependabot badge because it's broken

- src/main/java/com/agonyforge/arbitrader/service/TickerService.java
- src/test/java/com/agonyforge/arbitrader/service/SpreadServiceTest.java
- src/test/java/com/agonyforge/arbitrader/service/TickerServiceTest.java
These are much more likely to be an API error of some kind rather than the exchange buying or selling coins for free.
Fixes #507
> invalidate tickers where price is exactly equal to zero

- src/main/java/com/agonyforge/arbitrader/service/LiquidityException.java
- src/main/java/com/agonyforge/arbitrader/service/TradingService.java
- src/test/java/com/agonyforge/arbitrader/service/TradingServiceTest.java
In cases where `getLimitPrice()` could not fetch the order book because of rate limiting (ie. 429 from the server) the resulting exception would not be caught properly and showed a message telling the user that the exchange did not have enough liquidity. This change improves the error handling so that we show more appropriate error messages when errors occur in this method.
> Liquidity error handling
